version: "3"
services:

# TEMP NOT COMPLETE

api:
  image: redis:alpine
  ports:
    - "8080"
  networks:
    - frontend
  deploy:
    replicas: 2
    update_config:
      parallelism: 2
      delay: 10s
    restart_policy:
      condition: on-failure