version: "3"

services:

# API container   
  api:
    image: bencuk/angular-demoapp-api
    build: ./api
    ports:
    - "8080:8080"
    environment: 
    - APPSETTING_STORAGE_ACCOUNT=${APPSETTING_STORAGE_ACCOUNT}
    - APPSETTING_STORAGE_KEY=${APPSETTING_STORAGE_KEY}
  app:
    image: bencuk/angular-demoapp
    build: .
    ports: 
    - "3000:3000"
    environment: 
    - APPSETTING_API_ENDPOINT=http://localhost:8080/goats