version: "3"

services:
  # Container serving the Angular app from Node
  app-server-dev:
    image: bencuk/angular-demoapp:dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    networks:
     - frontend
networks: 
  frontend: